apiVersion: v1 # API Version of Service resource kind
kind: Service # Service Kind
metadata:
    name: app-nginx-service # Define the name of the Service
spec:
    type: NodePort # Define the service as an NodePort
    ports:
        - port: 80 # Define on which port the Service can be reached
    selector:
        app: app-nginx # Define to what the Service should be identified as.
--- # Defining new Object
apiVersion: apps/v1 # API Version of Deployment resource kind
kind: Deployment # Deployment Kind
metadata:
    name: app-nginx-deployment # Define the name of the Deployment
spec:
    replicas: 3 # Create 3 Replica's
    selector:
        matchLabels:
            app: app-nginx # Determination for which Deployment the Pods will be apart of.
    template:
        metadata:
            labels:
                app: app-nginx # The name we are giving to the App
        spec:
            containers:
                - name: nginx # The name we want to give to the Container
                  image: nginx:1.17.3 # The image we want to use for this Container
                  ports:
                      - containerPort: 80 # The port we want to use for the Deployment and how it can be accessed
