version: '3'

services:
    web:
        build: .
        command: npm run dev
        ports:
            - '3000:3000' # expose 3000 on host and sent to 3000 in container
        volumes:
            - .:/usr/src/app/
            - /usr/src/app/node_modules
